name: Produce artifact

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  produce-artifact:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: "echo Hello, world! >> a.log"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          # Artifact name
          name: a-log
          # A file, directory or wildcard pattern that describes what to upload
          path: a.log
          retention-days: 1
